# Use root/example as user/password credentials
version: '8.0'

name : microservice-db

services:

  auth-db:
    image: mongo
    container_name: auth-db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Hayato360

  item-db:
    image: mongo
    container_name: item-db
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Hayato360

  player-db:
    image: mongo
    container_name: player-db
    ports:
      - 27019:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Hayato360

  inventory-db:
    image: mongo
    container_name: inventory-db
    ports:
      - 27020:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Hayato360
      
  payment-db:
    image: mongo
    container_name: payment-db
    ports:
      - 27021:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Hayato360


